.TH SASSDOCIFY 1
.
.SH NAME
.
sassdocify \- make a SassDoc branch
.
.SH SYNOPSIS
.
\fBsassdocify\fP [\fIoptions\fP] [\fIsrc\fP]
.
.SH DESCRIPTION
\fBsassdocify\fP creates a \fIgh-pages\fP branch in the current
\fBgit\fP(1) repository, and documentize the \fIsrc\fP directory
within it.

If \fIsrc\fP is not given, it's set to the current directory.
.
.SH OPTIONS
.
.TP
.BR -h ", " --help
Show help.
.
.TP
.BR -V ", " --version
Show version.

.TP
.BI -m " MSG" "\fR,\fP --message="MSG
Show version.
.
.SH SEE ALSO
\fBgit\fP(1), \fIhttp://sassdoc.com/\fP
